"""
Master source configuration for the UP Political Intelligence Pipeline.
Includes all RSS feeds and HTML topic/district pages as specified.
"""

RSS_FEEDS = [
    # State-level feeds
    ("bhaskar",         "https://www.bhaskar.com/rss-feed/2322/"),
    ("patrika",         "https://cms.patrika.com/blog/location/lucknow-news/feed/"),
    ("patrika",         "https://cms.patrika.com/blog/location/uttar-pradesh/feed/"),
    ("news18",          "https://hindi.news18.com/rss/uttar-pradesh.xml"),
    ("zeenews",         "https://zeenews.india.com/hindi/india/up-uttarakhand/rss.xml"),
    ("livehindustan",   "https://www.livehindustan.com/rss/state/uttar-pradesh"),
    ("abplive",         "https://www.abplive.com/states/up-uk/feed"),
    ("ndtv",            "https://ndtv.in/uttar-pradesh/rss"),
    ("jagran",          "https://english.jagran.com/rss/politics.xml"),
    # Social / X bridges
    ("x_twitter",       "https://rsshub.app/twitter/user/yadavakhilesh"),
    ("x_twitter",       "https://rsshub.app/twitter/user/myogiadityanath"),
    ("x_twitter",       "https://rsshub.app/twitter/user/Mayawati"),
    ("x_twitter",       "https://rsshub.app/twitter/user/RahulGandhi"),
    ("x_twitter",       "https://rsshub.app/twitter/user/priyankagandhi"),
]

# HTML pages to extract article links from.
# Format: (source_name, url, district_tag)
HTML_TOPIC_PAGES = [
    # ── AajTak (District pages) ──────────────────────────────────────
    ("aajtak","https://www.aajtak.in/topic/saharanpur","saharanpur"),
    ("aajtak","https://www.aajtak.in/topic/shamli","shamli"),
    ("aajtak","https://www.aajtak.in/topic/muzaffarnagar","muzaffarnagar"),
    ("aajtak","https://www.aajtak.in/topic/bijnor","bijnor"),
    ("aajtak","https://www.aajtak.in/topic/moradabad","moradabad"),
    ("aajtak","https://www.aajtak.in/topic/sambhal","sambhal"),
    ("aajtak","https://www.aajtak.in/topic/rampur","rampur"),
    ("aajtak","https://www.aajtak.in/topic/amroha","amroha"),
    ("aajtak","https://www.aajtak.in/topic/meerut","meerut"),
    ("aajtak","https://www.aajtak.in/topic/baghpat","baghpat"),
    ("aajtak","https://www.aajtak.in/topic/ghaziabad","ghaziabad"),
    ("aajtak","https://www.aajtak.in/topic/hapur","hapur"),
    ("aajtak","https://www.aajtak.in/topic/gautam-buddha-nagar","gautam-buddha-nagar"),
    ("aajtak","https://www.aajtak.in/topic/bulandshahar","bulandshahar"),
    ("aajtak","https://www.aajtak.in/topic/aligarh","aligarh"),
    ("aajtak","https://www.aajtak.in/topic/hathras","hathras"),
    ("aajtak","https://www.aajtak.in/topic/mathura","mathura"),
    ("aajtak","https://www.aajtak.in/topic/agra","agra"),
    ("aajtak","https://www.aajtak.in/topic/firozabad","firozabad"),
    ("aajtak","https://www.aajtak.in/topic/kasganj","kasganj"),
    ("aajtak","https://www.aajtak.in/topic/etah","etah"),
    ("aajtak","https://www.aajtak.in/topic/mainpuri","mainpuri"),
    ("aajtak","https://www.aajtak.in/topic/budaun","budaun"),
    ("aajtak","https://www.aajtak.in/topic/bareilly","bareilly"),
    ("aajtak","https://www.aajtak.in/topic/pilibhit","pilibhit"),
    ("aajtak","https://www.aajtak.in/topic/shahjahanpur","shahjahanpur"),
    ("aajtak","https://www.aajtak.in/topic/lakhimpur-kheri","lakhimpur-kheri"),
    ("aajtak","https://www.aajtak.in/topic/sitapur","sitapur"),
    ("aajtak","https://www.aajtak.in/topic/hardoi","hardoi"),
    ("aajtak","https://www.aajtak.in/topic/unnao","unnao"),
    ("aajtak","https://www.aajtak.in/topic/lucknow","lucknow"),
    ("aajtak","https://www.aajtak.in/topic/raebareli","raebareli"),
    ("aajtak","https://www.aajtak.in/topic/amethi","amethi"),
    ("aajtak","https://www.aajtak.in/topic/sultanpur","sultanpur"),
    ("aajtak","https://www.aajtak.in/topic/farrukhabad","farrukhabad"),
    ("aajtak","https://www.aajtak.in/topic/kannauj","kannauj"),
    ("aajtak","https://www.aajtak.in/topic/etawah","etawah"),
    ("aajtak","https://www.aajtak.in/topic/auraiya","auraiya"),
    ("aajtak","https://www.aajtak.in/topic/kanpur-dehat","kanpur-dehat"),
    ("aajtak","https://www.aajtak.in/topic/kanpur-nagar","kanpur-nagar"),
    ("aajtak","https://www.aajtak.in/topic/jalaun","jalaun"),
    ("aajtak","https://www.aajtak.in/topic/jhansi","jhansi"),
    ("aajtak","https://www.aajtak.in/topic/lalitpur","lalitpur"),
    ("aajtak","https://www.aajtak.in/topic/hamirpur","hamirpur"),
    ("aajtak","https://www.aajtak.in/topic/mahoba","mahoba"),
    ("aajtak","https://www.aajtak.in/topic/banda","banda"),
    ("aajtak","https://www.aajtak.in/topic/chitrakoot","chitrakoot"),
    ("aajtak","https://www.aajtak.in/topic/fatehpur","fatehpur"),
    ("aajtak","https://www.aajtak.in/topic/pratapgarh","pratapgarh"),
    ("aajtak","https://www.aajtak.in/topic/kaushambi","kaushambi"),
    ("aajtak","https://www.aajtak.in/topic/prayagraj","prayagraj"),
    ("aajtak","https://www.aajtak.in/topic/barabanki","barabanki"),
    ("aajtak","https://www.aajtak.in/topic/ayodhya","ayodhya"),
    ("aajtak","https://www.aajtak.in/topic/ambedkar-nagar","ambedkar-nagar"),
    ("aajtak","https://www.aajtak.in/topic/bahraich","bahraich"),
    ("aajtak","https://www.aajtak.in/topic/shravasti","shravasti"),
    ("aajtak","https://www.aajtak.in/topic/balrampur","balrampur"),
    ("aajtak","https://www.aajtak.in/topic/gonda","gonda"),
    ("aajtak","https://www.aajtak.in/topic/siddharthnagar","siddharthnagar"),
    ("aajtak","https://www.aajtak.in/topic/basti","basti"),
    ("aajtak","https://www.aajtak.in/topic/sant-kabir-nagar","sant-kabir-nagar"),
    ("aajtak","https://www.aajtak.in/topic/maharajganj","maharajganj"),
    ("aajtak","https://www.aajtak.in/topic/gorakhpur","gorakhpur"),
    ("aajtak","https://www.aajtak.in/topic/kushinagar","kushinagar"),
    ("aajtak","https://www.aajtak.in/topic/deoria","deoria"),
    ("aajtak","https://www.aajtak.in/topic/azamgarh","azamgarh"),
    ("aajtak","https://www.aajtak.in/topic/mau","mau"),
    ("aajtak","https://www.aajtak.in/topic/ballia","ballia"),
    ("aajtak","https://www.aajtak.in/topic/jaunpur","jaunpur"),
    ("aajtak","https://www.aajtak.in/topic/ghazipur","ghazipur"),
    ("aajtak","https://www.aajtak.in/topic/chandauli","chandauli"),
    ("aajtak","https://www.aajtak.in/topic/varanasi","varanasi"),
    ("aajtak","https://www.aajtak.in/topic/bhadohi","bhadohi"),
    ("aajtak","https://www.aajtak.in/topic/mirzapur","mirzapur"),
    ("aajtak","https://www.aajtak.in/topic/sonbhadra","sonbhadra"),

    # ── UP Tak ───────────────────────────────────────────────────────
    ("uptak","https://www.uptak.in/politics","UP"),
    ("uptak","https://www.uptak.in/neighbouring-news/agra","agra"),
    ("uptak","https://www.uptak.in/neighbouring-news/ayodhya","ayodhya"),
    ("uptak","https://www.uptak.in/neighbouring-news/kanpur","kanpur"),
    ("uptak","https://www.uptak.in/neighbouring-news/gorakhpur","gorakhpur"),
    ("uptak","https://www.uptak.in/neighbouring-news/gautam-buddh-nagar","gautam-buddha-nagar"),
    ("uptak","https://www.uptak.in/neighbouring-news/jhansi","jhansi"),
    ("uptak","https://www.uptak.in/neighbouring-news/prayagraj","prayagraj"),
    ("uptak","https://www.uptak.in/neighbouring-news/mathura","mathura"),
    ("uptak","https://www.uptak.in/neighbouring-news/meerut","meerut"),
    ("uptak","https://www.uptak.in/neighbouring-news/lucknow","lucknow"),
    ("uptak","https://www.uptak.in/neighbouring-news/varanasi","varanasi"),

    # ── Navbharat Times ───────────────────────────────────────────────
    ("navbharattimes","https://navbharattimes.indiatimes.com/metro/lucknow/articlelist/21248218.cms","lucknow"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/noida/articlelist/2313728.cms","noida"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/agra/articlelist/61483684.cms","agra"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/mathura/articlelist/19928262.cms","mathura"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/ghaziabad/articlelist/2287639.cms","ghaziabad"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/meerut/articlelist/11364157.cms","meerut"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/gorakhpur/articlelist/61483701.cms","gorakhpur"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/ayodhya/articlelist/19987335.cms","ayodhya"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/allahabad/articlelist/5195544.cms","prayagraj"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/varanasi/articlelist/61483673.cms","varanasi"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/kanpur/articlelist/5194950.cms","kanpur"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/saharanpur/articlelist/19928210.cms","saharanpur"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/bareilly/articlelist/75575203.cms","bareilly"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/moradabad/articlelist/75575184.cms","moradabad"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/raebareli/articlelist/75575044.cms","raebareli"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/azamgarh/articlelist/75575106.cms","azamgarh"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/muzaffarnagar/articlelist/75574943.cms","muzaffarnagar"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/lakhimpur-kheri/articlelist/92989844.cms","lakhimpur-kheri"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/jaunpur/articlelist/92989849.cms","jaunpur"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/ballia/articlelist/92989796.cms","ballia"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/bahraich/articlelist/92989786.cms","bahraich"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/basti/articlelist/92989793.cms","basti"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/jhansi/articlelist/92989606.cms","jhansi"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/etawah/articlelist/92989625.cms","etawah"),
    ("navbharattimes","https://navbharattimes.indiatimes.com/state/uttar-pradesh/varanasi/articlelist/61483673.cms","varanasi"),

    # ── Dainik Bhaskar (all 75 districts) ────────────────────────────
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/saharanpur","saharanpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/shamli","shamli"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/muzaffarnagar","muzaffarnagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/bijnor","bijnor"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/moradabad","moradabad"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/sambhal","sambhal"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/rampur","rampur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/amroha","amroha"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/meerut","meerut"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/baghpat","baghpat"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/ghaziabad","ghaziabad"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/hapur","hapur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/gautam-buddha-nagar","gautam-buddha-nagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/bulandshahar","bulandshahar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/aligarh","aligarh"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/hathras","hathras"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/mathura","mathura"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/agra","agra"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/firozabad","firozabad"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/kasganj","kasganj"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/etah","etah"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/mainpuri","mainpuri"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/budaun","budaun"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/bareilly","bareilly"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/pilibhit","pilibhit"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/shahjahanpur","shahjahanpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/lakhimpur-kheri","lakhimpur-kheri"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/sitapur","sitapur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/hardoi","hardoi"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/unnao","unnao"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/lucknow","lucknow"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/raebareli","raebareli"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/amethi","amethi"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/sultanpur","sultanpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/farrukhabad","farrukhabad"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/kannauj","kannauj"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/etawah","etawah"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/auraiya","auraiya"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/kanpur-dehat","kanpur-dehat"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/kanpur-nagar","kanpur-nagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/jalaun","jalaun"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/jhansi","jhansi"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/lalitpur","lalitpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/hamirpur","hamirpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/mahoba","mahoba"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/banda","banda"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/chitrakoot","chitrakoot"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/fatehpur","fatehpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/pratapgarh","pratapgarh"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/kaushambi","kaushambi"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/prayagraj","prayagraj"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/barabanki","barabanki"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/ayodhya","ayodhya"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/ambedkar-nagar","ambedkar-nagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/bahraich","bahraich"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/shravasti","shravasti"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/balrampur","balrampur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/gonda","gonda"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/siddharthnagar","siddharthnagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/basti","basti"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/sant-kabir-nagar","sant-kabir-nagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/maharajganj","maharajganj"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/gorakhpur","gorakhpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/kushinagar","kushinagar"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/deoria","deoria"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/azamgarh","azamgarh"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/mau","mau"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/ballia","ballia"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/jaunpur","jaunpur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/ghazipur","ghazipur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/chandauli","chandauli"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/varanasi","varanasi"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/bhadohi","bhadohi"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/mirzapur","mirzapur"),
    ("bhaskar","https://www.bhaskar.com/local/uttar-pradesh/sonbhadra","sonbhadra"),

    # ── Jagran ────────────────────────────────────────────────────────
    ("jagran","https://www.jagran.com/uttar-pradesh/kanpur-city","kanpur"),
    ("jagran","https://www.jagran.com/uttar-pradesh/lucknow-city","lucknow"),
    ("jagran","https://www.jagran.com/uttar-pradesh/meerut-city","meerut"),
    ("jagran","https://www.jagran.com/uttar-pradesh/amethi","amethi"),
    ("jagran","https://www.jagran.com/uttar-pradesh/agra-city","agra"),
    ("jagran","https://www.jagran.com/uttar-pradesh/prayagraj","prayagraj"),
    ("jagran","https://www.jagran.com/uttar-pradesh/aligarh-city","aligarh"),
    ("jagran","https://www.jagran.com/uttar-pradesh/azamgarh","azamgarh"),
    ("jagran","https://www.jagran.com/uttar-pradesh/ambedkarnagar","ambedkar-nagar"),
    ("jagran","https://www.jagran.com/uttar-pradesh/ballia","ballia"),
    ("jagran","https://www.jagran.com/uttar-pradesh/gorakhpur-city","gorakhpur"),
    ("jagran","https://www.jagran.com/uttar-pradesh/varanasi-city","varanasi"),
    ("jagran","https://www.jagran.com/uttar-pradesh/jhansi-city","jhansi"),
    ("jagran","https://www.jagran.com/uttar-pradesh/ayodhya","ayodhya"),
    ("jagran","https://www.jagran.com/uttar-pradesh/ghaziabad","ghaziabad"),
    ("jagran","https://www.jagran.com/uttar-pradesh/noida","gautam-buddha-nagar"),
    ("jagran","https://www.jagran.com/uttar-pradesh/bareilly-city","bareilly"),
    ("jagran","https://www.jagran.com/uttar-pradesh/moradabad-city","moradabad"),
    ("jagran","https://www.jagran.com/uttar-pradesh/saharanpur","saharanpur"),
    ("jagran","https://www.jagran.com/uttar-pradesh/muzaffarnagar","muzaffarnagar"),
    ("jagran","https://www.jagran.com/uttar-pradesh/mathura","mathura"),
    ("jagran","https://www.jagran.com/uttar-pradesh/raebareli","raebareli"),
    ("jagran","https://www.jagran.com/uttar-pradesh/sultanpur","sultanpur"),
    ("jagran","https://www.jagran.com/uttar-pradesh/pratapgarh","pratapgarh"),
    ("jagran","https://www.jagran.com/uttar-pradesh/bulandshahr","bulandshahar"),

    # ── Punjab Kesari ─────────────────────────────────────────────────
    ("punjabkesari","https://up.punjabkesari.in/lucknow","lucknow"),
    ("punjabkesari","https://up.punjabkesari.in/varanasi","varanasi"),
    ("punjabkesari","https://up.punjabkesari.in/kanpur","kanpur"),
    ("punjabkesari","https://up.punjabkesari.in/meerut","meerut"),
    ("punjabkesari","https://up.punjabkesari.in/agra","agra"),
    ("punjabkesari","https://up.punjabkesari.in/prayagraj","prayagraj"),
    ("punjabkesari","https://up.punjabkesari.in/jhansi","jhansi"),
    ("punjabkesari","https://up.punjabkesari.in/gorakhpur","gorakhpur"),
    ("punjabkesari","https://up.punjabkesari.in/up-sp","SP"),
    ("punjabkesari","https://up.punjabkesari.in/up-bsp","BSP"),
    ("punjabkesari","https://up.punjabkesari.in/up-bjp","BJP"),
    ("punjabkesari","https://up.punjabkesari.in/up-congress","INC"),

    # ── OneIndia ──────────────────────────────────────────────────────
    ("oneindia","https://hindi.oneindia.com/news/lucknow/","lucknow"),
    ("oneindia","https://hindi.oneindia.com/news/varanasi/","varanasi"),
    ("oneindia","https://hindi.oneindia.com/news/allahabad/","prayagraj"),
    ("oneindia","https://hindi.oneindia.com/news/kanpur/","kanpur"),
    ("oneindia","https://hindi.oneindia.com/news/agra/","agra"),
    ("oneindia","https://hindi.oneindia.com/news/gorakhpur/","gorakhpur"),
    ("oneindia","https://hindi.oneindia.com/news/meerut/","meerut"),
    ("oneindia","https://hindi.oneindia.com/news/noida/","noida"),
    ("oneindia","https://hindi.oneindia.com/news/azamgarh/","azamgarh"),
    ("oneindia","https://hindi.oneindia.com/news/mathura/","mathura"),
    ("oneindia","https://hindi.oneindia.com/news/aligarh/","aligarh"),
    ("oneindia","https://hindi.oneindia.com/news/jhansi/","jhansi"),

    # ── ABP Ganga ─────────────────────────────────────────────────────
    ("abplive","https://www.abplive.com/topic/lucknow","lucknow"),
    ("abplive","https://www.abplive.com/topic/varanasi","varanasi"),
    ("abplive","https://www.abplive.com/topic/agra","agra"),
    ("abplive","https://www.abplive.com/topic/kanpur","kanpur"),
    ("abplive","https://www.abplive.com/topic/meerut","meerut"),
    ("abplive","https://www.abplive.com/topic/noida","noida"),
    ("abplive","https://www.abplive.com/topic/prayagraj","prayagraj"),
    ("abplive","https://www.abplive.com/topic/ghaziabad","ghaziabad"),
    ("abplive","https://www.abplive.com/topic/ayodhya","ayodhya"),

    # ── Times Now Navbharat ───────────────────────────────────────────
    ("timesnowhindi","https://www.timesnowhindi.com/cities/lucknow-news","lucknow"),
    ("timesnowhindi","https://www.timesnowhindi.com/cities/varanasi-news","varanasi"),
    ("timesnowhindi","https://www.timesnowhindi.com/cities/agra-news","agra"),
    ("timesnowhindi","https://www.timesnowhindi.com/cities/noida-news","noida"),
]
